### converts categorical column to numeric features


In [85]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [87]:
## Create a simple dataframe 
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [89]:
df['color'].shape

(6,)

In [91]:
df

color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [93]:
df[['color']].shape

(6, 1)

In [95]:
encoder=OneHotEncoder()
encoded =encoder.fit_transform(df[['color']]).toarray() ## arranged alphabetically

In [99]:
encoded1 =encoder.fit_transform(df[['color']]) ## arranged alphabetically
encoded1

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [97]:
?encoder.fit_transform

Signature: encoder.fit_transform(X, y=None, **fit_params)
Docstring:
Fit to data, then transform it.

Fits transformer to `X` and `y` with optional parameters `fit_params`
and returns a transformed version of `X`.

Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input samples.

y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
    Target values (None for unsupervised transformations).

**fit_params : dict
    Additional fit parameters.

Returns
-------
X_new : ndarray array of shape (n_samples, n_features_new)
    Transformed array.
File:      /opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py
Type:      method

In [29]:
encoded 

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [33]:
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [35]:
encoded_df

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [39]:
#for new data
encoder.transform([['blue']]).toarray()

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [41]:
pd.concat([df,encoded_df],axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [47]:
import seaborn as sns

In [49]:
tips_df = sns.load_dataset('tips')

In [51]:
tips_df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [67]:
tips_df.isnull()

total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [73]:
tips_df[tips_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size]
Index: []

In [55]:
encoded_tips = encoder.fit_transform(tips_df[['sex','smoker','day','time']]).toarray()

In [75]:
encoded_tips

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [79]:
encoded_tips_df=pd.DataFrame(encoded_tips,columns=encoder.get_feature_names_out())

In [81]:
encoded_tips_df

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
..          ...       ...        ...         ...      ...      ...      ...   
239         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
240         1.0       0.0        0.0         1.0      0.0      1.0      0.0   
241         0.0       1.0        0.0         1.0      0.0      1.0      0.0   
242         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
243         1.0       0.0        1.0         0.0      0.0      0.0      0.0   

     day_Thur  time_Dinner  time_Lunch  
0         0.0          1.0         0.0  
1         0.0          1.0         0.0  
2         0.0          1.0         0.0  
3         0.0          1.0         0.0  
4         0.0          1.0         0.0  
..        ...          ...         ...  
239       0.0          1.0         0.0  
240       0.0          1.0         0.0  
241       0.0          1.0         0.0  
242       0.0          1.0         0.0  
243       1.0          1.0         0.0  

[244 rows x 10 columns]

In [83]:
pd.concat([tips_df,encoded_tips_df],axis=1)

total_bill   tip     sex smoker   day    time  size  sex_Female  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0   
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0   

     sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  \
0         0.0        1.0         0.0      0.0      0.0      1.0       0.0   
1         1.0        1.0         0.0      0.0      0.0      1.0       0.0   
2         1.0        1.0         0.0      0.0      0.0      1.0       0.0   
3         1.0        1.0         0.0      0.0      0.0      1.0       0.0   
4         0.0        1.0         0.0      0.0      0.0      1.0       0.0   
..        ...        ...         ...      ...      ...      ...       ...   
239       1.0        1.0         0.0      0.0      1.0      0.0       0.0   
240       0.0        0.0         1.0      0.0      1.0      0.0       0.0   
241       1.0        0.0         1.0      0.0      1.0      0.0       0.0   
242       1.0        1.0         0.0      0.0      1.0      0.0       0.0   
243       0.0        1.0         0.0      0.0      0.0      0.0       1.0   

     time_Dinner  time_Lunch  
0            1.0         0.0  
1            1.0         0.0  
2            1.0         0.0  
3            1.0         0.0  
4            1.0         0.0  
..           ...         ...  
239          1.0         0.0  
240          1.0         0.0  
241          1.0         0.0  
242          1.0         0.0  
243          1.0         0.0  

[244 rows x 17 columns]